name: licenta
description: easy_booking
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  animations: ^2.0.3
  auto_route: ^5.0.4
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.2
  calendar_date_picker2: ^0.5.2
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^2.0.1
  dartz: ^0.10.1
  dev: ^1.0.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  email_validator: ^2.0.1
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  firebase_database: ^10.2.2
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_multi_formatter: ^2.5.7
  flutter_secure_storage: ^7.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.0
  freezed_annotation: ^2.0.3
  image_picker: ^0.8.8
  intl: ^0.18.0
  json_serializable: ^6.2.0
  modal_bottom_sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet.git
      ref: 38c6f44d0c4205608618a676a907c2d104d00b52
      path: modal_bottom_sheet

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_annotation: ^4.5.0
  very_good_analysis: ^3.1.0


flutter:
  uses-material-design: true

  assets:
    - asset/image/

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/Poppins-Regular.ttf
        - asset: asset/font/Poppins-Medium.ttf
          weight: 500
        - asset: asset/font/Poppins-SemiBold.ttf
          weight: 600

