name: licenta
description: easy_booking

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/image/

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/Poppins-Regular.ttf
        - asset: asset/font/Poppins-Medium.ttf
          weight: 500
        - asset: asset/font/Poppins-SemiBold.ttf
          weight: 600

